name: Bug Tracker Integration

on:
  push:
    branches: [main, master, dev, development, staging]
  pull_request:
    branches: [main, master]

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup environment based on project type
      - name: Setup Node.js
        uses: actions/setup-node@v3
        if: hashFiles('package.json') != ''
        with:
          node-version: "16"

      - name: Setup Python
        uses: actions/setup-python@v4
        if: hashFiles('requirements.txt') != '' || hashFiles('pyproject.toml') != ''
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          if [ -f "package.json" ]; then
            npm install
          elif [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          elif [ -f "pyproject.toml" ]; then
            pip install -e .
          fi

      # Run tests and capture output
      - name: Run tests
        id: run-tests
        continue-on-error: true
        run: |
          if [ -f "package.json" ]; then
            npm test 2>&1 | tee test-output.txt
          elif [ -f "pytest.ini" ] || [ -d "tests" ]; then
            python -m pytest -v 2>&1 | tee test-output.txt
          else
            echo "No recognized test framework found"
            exit 1
          fi

      # Report test failures if tests failed
      - name: Report test failures
        if: steps.run-tests.outcome == 'failure'
        run: |
          cat test-output.txt | base64 > encoded-output.txt
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.BUG_TRACKER_API_KEY }}" \
            -d "{\"projectId\": \"${{ secrets.BUG_TRACKER_PROJECT_ID }}\", \"commit\": \"${{ github.sha }}\", \"branch\": \"${{ github.ref_name }}\", \"repository\": \"${{ github.repository }}\", \"testOutput\": \"$(cat encoded-output.txt)\"}" \
            https://your-bug-tracker-domain.com/api/ci-report
